### ISSUE TITLE
HealthCheckTagHelper

### ISSUE THREAD

**Issue by JuergenGutsch** [aspnet/HealthChecks#26]
I proposed a HealthCheckTagHelper in the old repository:
https://github.com/aspnet/AspLabs/pull/17

I would recreate the PR for this repository too. But currently I'm not sure whether to place it in the Microsoft.Extensions.HealthChecks or in the Microsoft.AspNetCore.HealthChecks. 
Or even better to introduce a new project (Microsoft.AspNetCore.Mvc.HealthChecks) because a TagHelper needs dependencies to MVC and Razor and a Web API project which is using Microsoft.AspNetCore.Mvc.Core shouldn't have those dependencies.
What do you think @bradwilson?

**Comment by Eilon** [comment]
BTW I think you meant https://github.com/aspnet/AspLabs/pull/16.

I'm generally not a huge fan of tag helpers that are really just `if()` checks, unless they are there to do a relatively complex check. Even the `<environment>` tag helper is a bit dubious in nature in my mind.

Also, do we think it would be common to want to have this type of rendering in a page? I ask this because the fidelity of this tag helper is minimal: it's either healthy or it isn't. It provides no detail at all, so this tag helper doesn't help the visitor understand what's going on.

**Comment by JuergenGutsch** [comment]
You are right, it was 16 :)

Got it :) That's why I asked :) 
At the ASP.NET Hackathon last year at the MVP summit, we thought this TagHelper could be useful to provide user friendly information. Anyway, this could be easily done by the dev who uses the HealthChecks in his app.

Anything else I could contribute to this project?
